import { RouteInfo } from "./sidebar.metadata";
export const ADMIN_ROUTES: RouteInfo[] = [
  {
    path: "",
    title: "Admin",
    moduleName: "admin",
    iconType: "material-icons-two-tone",
    icon: "slideshow",
    class: "menu-toggle",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    submenu: [
      {
        path: "/admin/allbookings",
        title: "All Bookings",
        moduleName: "admin",
        iconType: "",
        icon: "",
        class: "ml-sub-sub-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        submenu: [],
      },
      {
        path: "/",
        title: "Room Settings",
        moduleName: "roomsettings",
        iconType: "",
        icon: "",
        class: "ml-sub-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        submenu: [
          {
            path: "/admin/roomsettings/rooms",
            title: "Rooms",
            moduleName: "roomsettings",
            iconType: "",
            icon: "",
            class: "ml-sub-sub-menu",
            groupTitle: false,
            badge: "",
            badgeClass: "",
            submenu: [],
          },
          {
            path: "/admin/roomsettings/extrafields",
            title: "Rooms Extra Fields",
            moduleName: "roomsettings",
            iconType: "",
            icon: "",
            class: "ml-sub-sub-menu",
            groupTitle: false,
            badge: "",
            badgeClass: "",
            submenu: [],
          },
          {
            path: "/admin/roomsettings/roomgroups",
            title: "Rooms Groups",
            moduleName: "roomsettings",
            iconType: "",
            icon: "",
            class: "ml-sub-sub-menu",
            groupTitle: false,
            badge: "",
            badgeClass: "",
            submenu: [],
          },
          {
            path: "/admin/roomsettings/permissiongroups",
            title: "Permission Groups",
            moduleName: "roomsettings",
            iconType: "",
            icon: "",
            class: "ml-sub-sub-menu",
            groupTitle: false,
            badge: "",
            badgeClass: "",
            submenu: [],
          },
          {
            path: "/admin/roomsettings/roles",
            title: "Roles",
            moduleName: "roomsettings",
            iconType: "",
            icon: "",
            class: "ml-sub-sub-menu",
            groupTitle: false,
            badge: "",
            badgeClass: "",
            submenu: [],
          },

          {
            path: "/admin/roomsettings/userinfo",
            title: "User Info",
            moduleName: "roomsettings",
            iconType: "",
            icon: "",
            class: "ml-sub-sub-menu",
            groupTitle: false,
            badge: "",
            badgeClass: "",
            submenu: [],
          },

          {
            path: "/admin/roomsettings/audit",
            title: "Audit",
            moduleName: "roomsettings",
            iconType: "",
            icon: "",
            class: "ml-sub-sub-menu",
            groupTitle: false,
            badge: "",
            badgeClass: "",
            submenu: [],
          },
        ],
      },
      {
        path: "/",
        title: "User Settings",
        moduleName: "usersettings",
        iconType: "",
        icon: "",
        class: "ml-sub-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        submenu: [
          {
            path: "/admin/usersettings/users",
            title: "Users",
            moduleName: "usersettings",
            iconType: "",
            icon: "",
            class: "ml-sub-sub-menu",
            groupTitle: false,
            badge: "",
            badgeClass: "",
            submenu: [],
          },
          {
            path: "/admin/usersettings/groups",
            title: "User Groups",
            moduleName: "usersettings",
            iconType: "",
            icon: "",
            class: "ml-sub-sub-menu",
            groupTitle: false,
            badge: "",
            badgeClass: "",
            submenu: [],
          },
        ],
      },
      {
        path: "/",
        title: "Closed Day Management",
        moduleName: "closeday",
        iconType: "",
        icon: "",
        class: "ml-sub-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        submenu: [
          {
            path: "/admin/closeday/closedday",
            title: "Closed Day",
            moduleName: "closeday",
            iconType: "",
            icon: "",
            class: "ml-sub-sub-menu",
            groupTitle: false,
            badge: "",
            badgeClass: "",
            submenu: [],
          },
        ],
      },
      {
        path: "/",
        title: "Email",
        moduleName: "email",
        iconType: "",
        icon: "",
        class: "ml-sub-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        submenu: [
          {
            path: "/admin/email/smtpsettings",
            title: "SMTP Settings",
            moduleName: "smtpsettings",
            iconType: "",
            icon: "",
            class: "ml-sub-sub-menu",
            groupTitle: false,
            badge: "",
            badgeClass: "",
            submenu: [],
          },
        ],
      },
    ],
  },
];
