import { RouteInfo } from "./sidebar.metadata";
export const ROUTES: RouteInfo[] = [
  {
    path: "/roomreservation",
    title: "Room Reservation",
    moduleName: "roomreservation",
    iconType: "material-icons-two-tone",
    icon: "home",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    submenu: [],
  },
  {
    path: "/mybookings",
    title: "My Bookings",
    moduleName: "mybookings",
    iconType: "material-icons-two-tone",
    icon: "home",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    submenu: [],
  },
  {
    path: "/myinfo",
    title: "My Info",
    moduleName: "myinfo",
    iconType: "material-icons-two-tone",
    icon: "account_circle",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    submenu: [],
  },
];
